# Generated by Django 4.0.6 on 2022-07-12 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=250)),
                ('vendor_url', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=250)),
                ('product_url', models.CharField(max_length=250, unique=True)),
                ('product_price', models.FloatField()),
                ('product_isOnSale', models.BooleanField(default=False)),
                ('product_salePrice', models.FloatField()),
                ('product_type', models.CharField(max_length=250)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.vendor')),
            ],
        ),
    ]
