# Generated by Django 4.0.6 on 2022-07-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_product_product_saleprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_salePrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
